name: SiegePal Snyk IaC
on:
  workflow_dispatch:
permissions:
  contents: read
  security-events: write
  actions: read
  checks: write
jobs:
  snyk-iac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Snyk CLI
        run: npm install -g snyk
      - name: Run Snyk IaC
        id: scan
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk iac test --sarif-file-output=snyk-iac.sarif
      - name: Upload SARIF
        if: always()
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-iac.sarif
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: siegepal-snyk_iac-results
          path: snyk-iac.sarif
